
com.opengamma.strata.pricer.curve.RatesCurveCalibrator:
  - standard
  - of:
      signature: "RatesCurveCalibrator of(double, double, int)"
  - calibrate:
      signature: ImmutableRatesProvider calibrate(RatesCurveGroupDefinition, MarketData, ReferenceData)
