
com.opengamma.strata.pricer.swap.DiscountingSwapProductPricer:
  - presentValue:
      signature: "CurrencyAmount presentValue(ResolvedSwap, Currency, RatesProvider)"

  - presentValueMultiCurrency:
      method: presentValue
      signature: "MultiCurrencyAmount presentValue(ResolvedSwap, RatesProvider)"

  - forecastValue
  - accruedInterest
  - parRate
  - parSpread

  - presentValueSensitivity:
      signature: "PointSensitivityBuilder presentValueSensitivity(ResolvedSwap, RatesProvider)"

  - forecastValueSensitivity
  - parRateSensitivity
  - parSpreadSensitivity
#  - cashFlows
  - explainPresentValue
  - currencyExposure
  - currentCash
