
com.opengamma.strata.market.curve.CurveName:
  - of

com.opengamma.strata.market.curve.RatesCurveGroupDefinition:
  - build
  - of:
      signature: "RatesCurveGroupDefinition of(CurveGroupName, Collection<RatesCurveGroupEntry>, Collection<CurveDefinition>)"

com.opengamma.strata.market.curve.RatesCurveGroupDefinitionBuilder:

com.opengamma.strata.market.curve.CurveGroupName:
  - of

com.opengamma.strata.market.curve.RatesCurveGroupEntry:
  - of:
      imports:
        - java.util.Arrays
        - java.util.Set
        - java.util.HashSet
      wrapper: |
                  RatesCurveGroupEntry of(CurveName curveName, Currency[] discountCurrencies, Index[] indices) {
                      RatesCurveGroupEntry.Builder builder = RatesCurveGroupEntry.builder();
                      builder.curveName(curveName);
                      if (null != discountCurrencies) {
                          Set<Currency> ccys = new HashSet<Currency>(Arrays.asList(discountCurrencies));
                          builder.discountCurrencies(ccys);
                      }
                      if (null != indices) {
                          Set<Index> idx = new HashSet<Index>(Arrays.asList(indices));
                          builder.indices(idx);
                      }
                      return builder.build();
                  }

com.opengamma.strata.market.curve.InterpolatedNodalCurveDefinition:
  - build

com.opengamma.strata.market.curve.CurveNodeDate:
  - of

com.opengamma.strata.market.curve.CurveNodeDateOrder:
  - of

com.opengamma.strata.market.curve.CurveNodeClashAction:
  - of
