
com.opengamma.strata.product.swap.PaymentRelativeTo:
  - of

com.opengamma.strata.product.swap.PaymentSchedule:
  - build

com.opengamma.strata.product.swap.CompoundingMethod:
  - of
  - toString:
      type: return_converter

com.opengamma.strata.product.swap.NotionalSchedule:
  - build

  - fixed:
      method: of
      signature: "NotionalSchedule of(Currency, double)"

  - of:
      signature: "NotionalSchedule of(Currency, ValueSchedule)"

com.opengamma.strata.product.swap.RateCalculation:

com.opengamma.strata.product.swap.FixedRateCalculation:
  - of

com.opengamma.strata.product.swap.IborRateCalculation:
  - of

com.opengamma.strata.product.swap.FxResetCalculation:
  - build

com.opengamma.strata.product.swap.FxResetFixingRelativeTo:
  - of

com.opengamma.strata.product.swap.PriceIndexCalculationMethod:
  - of

com.opengamma.strata.product.swap.RateCalculationSwapLeg:
  - build

com.opengamma.strata.product.swap.Swap:
  - of:
      signature: "Swap of(List<SwapLeg>)"

  - resolve

com.opengamma.strata.product.swap.ResolvedSwap:

com.opengamma.strata.product.swap.SwapLegType:
  - of
  - toString:
      type: return_converter
