
com.opengamma.strata.basics.schedule.PeriodicSchedule:
  - build

com.opengamma.strata.basics.schedule.Frequency:
  - parse
  - ofDays
  - ofWeeks
  - ofMonths
  - ofYears

com.opengamma.strata.basics.schedule.StubConvention:
  - of
  - toString:
      type: return_converter

com.opengamma.strata.basics.schedule.RollConvention:
  - of
  - getName:
      type: return_converter
