
#
# StandardId
#
com.opengamma.strata.basics.StandardId:
  - parse
  - of

#
# Reference Data
#
com.opengamma.strata.basics.ReferenceData:
  - standard
  - minimal
  - empty
  - combinedWith

#
# Dates
#
com.opengamma.strata.basics.date.BusinessDayConvention:
  - of

com.opengamma.strata.basics.date.BusinessDayAdjustment:
  - of
  - adjust
  - build

com.opengamma.strata.basics.date.HolidayCalendarId:
  - of
  - combinedWith

com.opengamma.strata.basics.date.AdjustableDate:
  - ofDate:
      method: of
      signature: "AdjustableDate of(LocalDate)"
      type: arg_converter

  - ofDateAndAdjustment:
      method: of
      signature: "AdjustableDate of(LocalDate, BusinessDayAdjustment)"

com.opengamma.strata.basics.date.DaysAdjustment:
  - build

  - ofCalendarDays:
      signature: "DaysAdjustment ofCalendarDays(int, BusinessDayAdjustment)"

  - ofBusinessDays:
      signature: "DaysAdjustment ofBusinessDays(int, HolidayCalendarId, BusinessDayAdjustment)"

com.opengamma.strata.basics.date.Tenor:
  - parse

#
# Schedules
#
com.opengamma.strata.basics.schedule.PeriodicSchedule:
  - build

com.opengamma.strata.basics.schedule.Frequency:
  - parse
  - ofDays
  - ofWeeks
  - ofMonths
  - ofYears

com.opengamma.strata.basics.schedule.StubConvention:
  - of

com.opengamma.strata.basics.schedule.RollConvention:
  - of



#
# Values
#
com.opengamma.strata.basics.value.ValueSchedule:
  - ofSteps:
      method: of
      signature: "ValueSchedule of(double, List<ValueStep>)"

  - ofSequence:
      method: of
      signature: "ValueSchedule of(double, ValueStepSequence)"

  - fixed:
      method: of
      signature: "ValueSchedule of(double)"
      type: arg_converter

com.opengamma.strata.basics.value.ValueAdjustment:
  - ofReplace
  - ofDeltaAmount
  - ofDeltaMultiplier
  - ofMultiplier
  - adjust

com.opengamma.strata.basics.value.ValueStep:
  - atPeriod:
      method: of
      signature: "ValueStep of(int, ValueAdjustment)"

  - atDate:
      method: of
      signature: "ValueStep of(LocalDate, ValueAdjustment)"

com.opengamma.strata.basics.value.ValueStepSequence:
  - of

#
# Currency
#
com.opengamma.strata.basics.currency.Currency:
  - of

com.opengamma.strata.basics.currency.CurrencyAmount:
  - parse
  - getCurrency
  - getAmount
  - of:
      signature: "CurrencyAmount of(Currency, double)"
  - zero:
      type: static

com.opengamma.strata.basics.currency.MultiCurrencyAmount:
  - getAmountOrZero
  - of:
      signature: "MultiCurrencyAmount of(Iterable<CurrencyAmount>)"

#
# DayCount
#
com.opengamma.strata.basics.date.DayCount:
  - of

#
# Indexes
#
com.opengamma.strata.basics.index.Index:

com.opengamma.strata.basics.index.OvernightIndex:
  - of

com.opengamma.strata.basics.index.IborIndex:
  - of

com.opengamma.strata.basics.index.FxIndex:
  - of
